version: "2.3"
services:
  # This name i.e. 'algorithm' must be correspond with the argument of `docker-compose` command.
  libraries:
    build:
      context: .
    # This image name must be correspond with the argument of `docker build` command.
    image: penguin-libraries
    volumes:
      - .:/root/penguin-libraries
      - /datadrive:/datadrive
    #   - /home/ubuntu/.ssh:/tmp/.ssh
    # command: cp -R /tmp/.ssh /root/
    ports:
      - "8888:8888"
    # nvidia-container-runtime must be installed by `sudo apt install nvidia-container-runtime`
    # write in /etc/docker/deamon.json
    # {
    #   "runtimes": {
    #     "nvidia": {
    #       "path": "nvidia-container-runtime",
    #       "runtimeArgs": []
    #     }
    #   }
    # }
    runtime: nvidia
    shm_size: 16g
    command: /bin/bash
    # command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
